## numpy와 닮은 파이토치(pytorch)

In [3]:
import torch
a=torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype) # data type -> 안에 있는 것의 자료형(여기선 1,2,3,4의 자료형을 의미)
print(a.shape) # print(a.size())랑 같은 결과
b=torch.tensor([1,2, 3.1   , 4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [5]:
A=torch.tensor([[1,2,3],[3,4,5]]) 
# A=torch.tensor([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원의 수 
print(A.numel()) # 전체 성분의 수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [4]:
print(torch.zeros(5))
print(torch.zeros_like(A)) # A랑 같은 shape의 행렬을 만들어준다
print(torch.ones(5))
print(torch.zeros(3,3))
print(torch.arange(3,10,2)) # range랑 같은데 tensor로 만들어줌 , 
print(torch.arange(0,1,0.1)) # 소수점 가능
print(torch.linspace(0,1,10)) # 0 에서부터 1 포함(default) 10개로

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [7]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b
print(c) # 드디어! 양 옆으로 길어지는 게 아닌 벡터의 합이 나옴! ->  numpy의 덧셈과 다르다.

tensor([5, 7, 9])


In [6]:
A=torch.tensor([[1,2,3],[1,2,3]])
B=torch.tensor([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C) 
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product) -> 실제 행렬의 곱과는 다르다.
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다 -> 실제 행렬의 곱과는 다르다.

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [8]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


## pytorch 의 인덱싱 슬라이스

In [8]:
a=torch.tensor([1,2,3,4,5,6,7,8,9]) 
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0]) 
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [10]:
# 행렬에 대한 인덱싱과 슬라이싱
A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) # 하나만 쓰면 '행'에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # ->여기서는 A[0][2]와 같은 결과가 나오지만 다른 case에서는 다른 결과 나올수있다.
              # (작동방식이 다르다. -> 밑에 중요!!부분 보기) 
              # 리스트와 달리 이런 것도 됨

B=[[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # error! -> 리스트에선 B[~,~] 슬라이싱 불가

print(A[1,:]) # 1 행, 전부 , A[a,b] -> a => a번째 행, b => b번째 열 -> 핵심 포인트!!!!
print(A[1,0:3:2])

# 중요!!(여기서 A[:,2]와 A[:][2]는 다른결과)---------------------------------------
print(A[:,2]) # 전부, 2 열
print(A[:][2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
----------------------------
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [12]:
# 3차원 행렬 인덱싱
A=torch.tensor([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,   
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A[0,1,2]) # A[a,b,c] -> a => a번째 채널 , b => b번째 행, c => c번째 열

a=torch.tensor(1) # 0차원
a_1=torch.tensor([1,2,3,4]) # 1D tensor -> 행렬도 아니고 벡터도 아니다.
a_2 = torch.tensor([[1,2,3,4]])
a_3 = torch.tensor([[[1,2,3,4]]])
print(a.shape)
print(a_1.shape)
print(a_2.shape)
print(a_3.shape) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다!

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor(6)
torch.Size([])
torch.Size([4])
torch.Size([1, 4])
torch.Size([1, 1, 4])


In [13]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A==3] = 100
print(A) # 그러면 이런 것도 가능하다! (3과 같은 애를 100으로 바꿔줘)

A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱 -> A[A==3]에서는 A와 A==3의 형태가 같았지만 여기선 행,열을 따로 생각해 해준다. 

b=torch.tensor([1,2,3,4])
print(b[[True,True,False,False]])
c=[1,2,3,4]
# c[[True,True,False,False]] # error! -> 그냥 리스트에선 안된다.

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [16]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[ torch.tensor(2) ] # torch.tensor를 안에다가?
print(A)

A=a[ torch.tensor([2,3,4]) ] # -> a의 2번째,3번째4번째를 가져온다.
print(A)
A=a[ torch.tensor([[2,2,2],[3,3,3]]) ] # -> shape에 맞게 값을 가져온다 -> 인덱싱된 애들로 2행 3열짜리 행렬을 만든다 
print(A)

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

# 주의깊게 보기!!
a=torch.tensor([[1,2,3],[4,5,6]])
print(a[0])
A=a[ torch.tensor([[0,1],[1,1]]) ]

print(A.shape) # 예를 들어, a[0] = tensor([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [13]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. torch.tensor(bool) ] => A와 같은 shape을 가지는 tensor형 bool이 어디에 True를 가지고 있냐
print(A[ torch.tensor([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐] -----------------------> 이렇게도 사용이 가능하다.
print(A[ [True,False,False,False], [False,True] ])
# 4. torch.tensor ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ torch.tensor([1,1,2,2,2]) ])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2])
tensor([2])
tensor([2])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])


## pytorch의 여러 함수들

In [14]:
A=torch.randn(3,3) # Normal 의 n , (평균0 ,분산 1) -> if 평균 10으로 하고싶으면 +10해주기, 분산100해주고 싶으면 10을 곱하기(var(x) = 1, var(10*x)=10*10*var(x)=100)
B=torch.rand(3,3)  # 이건 uniform,  (0부터 1사이) -> if -5부터 5사이 하고싶으면 -5해주기 
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0 번째 열이 음수인 행들

tensor([[ 0.5087, -0.3277,  1.5919],
        [ 1.7668, -1.6455,  0.9617],
        [-0.2354, -0.1724,  0.0155]])
tensor([[0.3362, 0.8400, 0.0632],
        [0.6985, 0.5289, 0.3308],
        [0.4202, 0.5947, 0.1670]])
tensor([[-0.2354, -0.1724,  0.0155]])


In [15]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A)) # ex) A=[[1,2],[3,4]] , torch.exp(A) = [[e^1,e^2],[e^3,e^4]] -> 각각에 대해서 적용
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # torch.exp(torch.tensor(1)) = e^1, torch.tensor(1)가 아닌 1이 들어가면 에러
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A,decimals = 2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[ 0.1671,  0.6493, -1.0987],
        [-0.0301, -0.0827, -0.2128],
        [-0.2929, -0.3184, -0.4005]])
tensor([[0.1671, 0.6493, 1.0987],
        [0.0301, 0.0827, 0.2128],
        [0.2929, 0.3184, 0.4005]])
tensor([[0.4087, 0.8058, 1.0482],
        [0.1734, 0.2875, 0.4613],
        [0.5412, 0.5643, 0.6328]])
tensor([[1.1818, 1.9141, 0.3333],
        [0.9704, 0.9207, 0.8083],
        [0.7461, 0.7273, 0.6700]])
tensor([[-1.7893, -0.4319,  0.0941],
        [-3.5047, -2.4929, -1.5472],
        [-1.2281, -1.1443, -0.9151]])
tensor(1.0000)
tensor(1.)
tensor(1.)
tensor([[ 0.,  1., -1.],
        [-0., -0., -0.],
        [-0., -0., -0.]])
tensor([[ 0.1700,  0.6500, -1.1000],
        [-0.0300, -0.0800, -0.2100],
        [-0.2900, -0.3200, -0.4000]])
tensor([[ 0.,  0., -2.],
        [-1., -1., -1.],
        [-1., -1., -1.]])
tensor([[ 1.,  1., -1.],
        [-0., -0., -0.],
        [-0., -0., -0.]])


In [16]:
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

# type(torch.pi) -> float임 , 만약 tensor와 연산하면 tensor로 바뀜
print(type(torch.pi/3))
print(type(torch.tensor(3)/3))

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)
<class 'float'>
<class 'torch.Tensor'>


In [17]:
torch.nan # not a number
print(torch.log(torch.tensor(-1)))

print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf]))) # torch.inf -> torch infinite (무한대)

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [18]:
# dim
import torch
A=torch.tensor([[[100,2,3,4],[5,6,7,8],[1,41,6,12]],[[32,56,10,0],[24,17,3,9],[5,4,61,13]]])
print(A)
# print(A.shape) # 결과 : torch.Size([2, 3, 4])

# print(A.max(dim=0))
# print(A.max(dim=1))
# print(A.max(dim=2))



tensor([[[100,   2,   3,   4],
         [  5,   6,   7,   8],
         [  1,  41,   6,  12]],

        [[ 32,  56,  10,   0],
         [ 24,  17,   3,   9],
         [  5,   4,  61,  13]]])


In [3]:
A=torch.randn(3,4)
print(A)
print(torch.max(A)) # a.max()와 같은 결과(-> a.max(dim=0)형태를 더 많이 쓴다)
print(torch.max(A,dim=0)) # -> dim은 numpy에서의 axis , 0번째 dim은 3, 1번째 dim은 4, 여기선 3개중 최댓값 1개를 골라라
print(torch.max(A,dim=1)) # 1D array로 바꿔버림
print(torch.max(A,dim=0, keepdims=True)) # keepdims -> 기존 차원 유지
print(torch.max(A,dim=1, keepdims=True)) # 3 행 1열 짜리 2D array
print(torch.min(A))
print(torch.min(A,dim=0))
print(torch.min(A,dim=1))
print(torch.argmax(A)) # -> 인덱스 반환
print(torch.argmax(A,dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(A,dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor([[-0.0316, -0.1095, -0.4702,  2.3332],
        [-1.7127, -0.3309,  0.3516, -0.1013],
        [-0.3014, -0.6416,  0.0091,  0.3984]])
tensor(2.3332)
torch.return_types.max(
values=tensor([-0.0316, -0.1095,  0.3516,  2.3332]),
indices=tensor([0, 0, 1, 0]))
torch.return_types.max(
values=tensor([2.3332, 0.3516, 0.3984]),
indices=tensor([3, 2, 3]))
torch.return_types.max(
values=tensor([[-0.0316, -0.1095,  0.3516,  2.3332]]),
indices=tensor([[0, 0, 1, 0]]))
torch.return_types.max(
values=tensor([[2.3332],
        [0.3516],
        [0.3984]]),
indices=tensor([[3],
        [2],
        [3]]))
tensor(-1.7127)
torch.return_types.min(
values=tensor([-1.7127, -0.6416, -0.4702, -0.1013]),
indices=tensor([1, 2, 0, 1]))
torch.return_types.min(
values=tensor([-0.4702, -1.7127, -0.6416]),
indices=tensor([2, 0, 1]))
tensor(3)
tensor([0, 0, 1, 0])
tensor([3, 2, 3])


In [20]:
a=torch.randn(6,1)
print(a)
print(torch.sort(a,dim=0)) # dim안주면 값 이상하게나온다(0번째 값을 기준으로 정렬한다.)
print(torch.sort(a,dim=0,descending=True)) # 내림차순
# torch.sort(a)와 a.sort()는 같은 결과 

tensor([[-1.4611],
        [ 0.0861],
        [-0.5760],
        [ 0.2032],
        [ 1.1331],
        [-3.3764]])
torch.return_types.sort(
values=tensor([[-3.3764],
        [-1.4611],
        [-0.5760],
        [ 0.0861],
        [ 0.2032],
        [ 1.1331]]),
indices=tensor([[5],
        [0],
        [2],
        [1],
        [3],
        [4]]))
torch.return_types.sort(
values=tensor([[ 1.1331],
        [ 0.2032],
        [ 0.0861],
        [-0.5760],
        [-1.4611],
        [-3.3764]]),
indices=tensor([[4],
        [3],
        [1],
        [2],
        [0],
        [5]]))


In [21]:
A=torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=1,keepdims=True))  # keepdims -> 기존 차원 유지
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A,dim=1,keepdims=True))
print(torch.std(A)) # standard deviation 표준 편차

print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

tensor([[-0.1418,  0.2250,  0.1637, -3.2711],
        [ 0.1321, -0.3229, -0.5249, -0.0862],
        [ 0.5705,  0.0555, -0.6887, -1.4121]])
tensor(-5.3010)
tensor([-3.0242, -0.8019, -1.4748])
tensor([[-3.0242],
        [-0.8019],
        [-1.4748]])
tensor(-0.4418)
tensor([-0.7561, -0.2005, -0.3687])
tensor([[-0.7561],
        [-0.2005],
        [-0.3687]])
tensor(1.0295)
tensor([[-3.0242],
        [-0.8019],
        [-1.4748]])
tensor([[-0.7561],
        [-0.2005],
        [-0.3687]])
tensor(1.0295)


In [22]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3) # 3부터 채우고 2 다음에 2를 채운다 -> 뒤에서 부터 채운다
print(B)
print(B.ndim) # 3 차원 행렬이다

tensor([3, 4, 2, 3, 2, 2, 3, 1, 2, 1, 2, 3])
torch.Size([12])
tensor([[[3, 4, 2],
         [3, 2, 2]],

        [[3, 1, 2],
         [1, 2, 3]]])
3


In [5]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)

# 2차원일떄
print(a.T@b) # 방법1
print(a.t()@b) # 방법2
print(a.transpose(1,0)@b) # 방법3
print(a.permute(1,0)@b) # 방법4 , permute(0번째 dim,1번째 dim,2번째 dim) 만약 permute(0,1,2)하면 그대로이고 permute(0,2,1)하면 행,열이 바뀐다.

# 3차원일때 permute사용법
A=torch.randn(4,3,6)
print(A.shape)
print(A.permute(0,2,1).shape)
print(A.transpose(0,2).shape) # transpose는 둘끼리 자리 바꾸기만 가능

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 3, 6])
torch.Size([4, 6, 3])
torch.Size([6, 3, 4])


In [24]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [6]:
x=torch.randn(2,3,4,5,6)
print(x.shape)
print(x[1,2,:,:,:].shape) 
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

torch.Size([2, 3, 4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [26]:
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))


# print(A)
# print(B)

# vstack과 hstack은 쓰지말기 -> 차원 많아지면 헷갈림 -> 밑에있는 cat을 쓰기
# C=torch.vstack([A,B]) # vstack은 dim=0
# D=torch.hstack([A,B]) # hstack은 dim=1

# cat
E=torch.cat([A,B],dim=0) # cat =  concatenate : 연결하다, # numpy의 block과 비슷한 역할
                        # dim=0 -> 0번째 dim에 쌓는다.   
F=torch.cat([A,B],dim=1)
G=torch.cat([A, B],dim = 2)

# print(C)
# print(D)

# print(E)
# print(G)
# print(G)


In [27]:
A = torch.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape)

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])
torch.Size([3, 4])


In [28]:
# unsqueeze -> squeeze랑 반대

A = torch.randn(3,4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)

print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [29]:
# unsqueeze응용
A=torch.ones(3,4)
B=torch.zeros(3,4)

A=A.unsqueeze(dim=0)
B=B.unsqueeze(dim=0)
C=torch.cat([A,B],dim=0) # 2차원을 행렬 2개를 가지고 3차원으로 만들기
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [30]:
A=torch.tensor([[1,2],[3,4]])
B=A # 주소가 같음
B[0,0]=100

print(B)
print(A)

A=torch.tensor([[1,2],[3,4]])
B=A.clone() # 주소가 다름
B[0,0]=100

print(B)
print(A)


tensor([[100,   2],
        [  3,   4]])
tensor([[100,   2],
        [  3,   4]])
tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


## @에 대해 좀만 더 

In [2]:
# 2차원일때
A=torch.randn(5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape)

torch.Size([5, 10])


In [3]:
# 3차원일때 -> 각 채널마다 @해준다 
A=torch.randn(32,5,7)
B=torch.randn(32,7,10)
C=A@B
print(C.shape) 

torch.Size([32, 5, 10])


In [ ]:
# repeat
A=torch.randn(32,5,7) # 3차원
B=torch.randn(7,10)   # 2차원

print(B.repeat(32,1,1).shape) # (1,7,10)으로 만든 후 32번 반복

C=A@B.repeat(32,1,1)
D=A@B # -> A,B형태달라도 작은차원을 큰차원에맞게 맞춰서 행렬곱해준다.

print(C.shape)
print(D.shape)

print((C-D).abs().max()) # 별로 차이 안난다 -> C와 D는 같다

torch.Size([32, 7, 10])
torch.Size([32, 5, 10])
torch.Size([32, 5, 10])
tensor(9.5367e-07)


In [ ]:
# repeat 자세히
# A=torch.rand(2,3)
A=torch.tensor([1,2,3,4,5,6]).reshape(2,3)
print(A.shape)
A_repeat = A.repeat(3,1,3,2) 

print(A)
print(A_repeat)
print(A_repeat.shape)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[[1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6],
          [1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6],
          [1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6]]],


        [[[1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6],
          [1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6],
          [1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6]]],


        [[[1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6],
          [1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6],
          [1, 2, 3, 1, 2, 3],
          [4, 5, 6, 4, 5, 6]]]])
torch.Size([3, 1, 6, 6])


## numpy <-> torch 왔다갔다 가능

In [3]:
import numpy as np
import torch

a=np.array([1,2,3])
b=torch.tensor([1,2,3])

# numpy를 tensor로 변경하는 방법
A = torch.tensor(a) # 방법1 -> 많이 쓰는 방법 

# A = torch.from_numpy(a) # 방법 2:  함수사용
print(type(A))

# tensor를 numpy로 변경하는 방법
B=np.array(b) # 방법 1
B=b.numpy() # 방법 2 -> 많이 쓰는 방법

print(type(B))


<class 'torch.Tensor'>
<class 'numpy.ndarray'>


### 딥러닝을 가능하게 한 autograd(자동미분) -- 중요!

In [20]:
x=torch.tensor([1.],requires_grad=True) # requires_grad=True -> 미분할것이라는 뜻 , 1.(1.0의미) 대신 1넣으면 에러 -> float이여야 해서
print(x)
print(x.requires_grad)

tensor([1.], requires_grad=True)
True


In [25]:
x=torch.tensor([1.],requires_grad=True) 
y=x**2
print(y) # PowBackward가 붙어있다!-> 미분되는것

print('x.grad : ',x.grad)

y.backward() # -> 미분해준것, y를 미분한 2x의 x값에 1을 대입한 것이 x.grad라는 attribute에 넣어둔다.

print('x.grad : ',x.grad) # x.grad -> y를 미분한 2x의 x값에 1을 대입한 gradient 값

# numercical gradient(미분 정의식 통해 미분)가 아니고 미분 공식을 미리 정해준것(ex)x**n미분 -> n*x**n-1)

tensor([1.], grad_fn=<PowBackward0>)
x.grad :  None
None
x.grad :  tensor([2.])


In [ ]:
x=torch.tensor([1.],requires_grad=True) 
y=x.argmax()
print(y) # grad_fn 안붙어있다 -> y함수가 grad_fn에 안들어있거나 미분이 불가능한것


tensor(0)


In [26]:
x=torch.tensor([1.],requires_grad=True) 
y=x**2
print(y)
# y.retain_grad() # 이걸 하면 y.grad도 볼수 있다.(y.requires_grad=True하면 에러 -> y는 leaf variable이 아니기 때문)
z=3*y
print(z) # MulBackward0가 붙어있다!(마지막 연산의 grad_fn만 나타나는거지 실제론 메모리에 이전 grad_fn들 저장돼있다. )

# chain rule통해 미분하는 것을 backward()통해 구현해놓았다.
z.backward() # z를 x로 미분한다 (requires_grad=True로 돼있는 애들로 미분하는것)

print(x.grad)
# print(y.grad) 
# -> y는 leaf Tensor(requires_grad=True 돼있는거)가 아니다 -> Warning이 나온다.-> y.retain_grad()코드를 추가해서 구해줄수있다.(위의 주석 코드)


tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])
tensor([3.])


In [ ]:
x=torch.tensor([1.],requires_grad=True) 
y=x**2
z=3*y

y.backward() # 이렇게 하면 y에서부터 뒤로 넘어감(backward!)
print(x.grad)

tensor([2.])


In [ ]:
x=torch.tensor([1.],requires_grad=True) 
a=x**2
b=a+1
print(b)# AddBackward0가 붙어있다!(가장 '마지막'에 연산되는게 붙어있다(여기선 +))
c=b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [ ]:
# 여러개의 변수일때 (편미분 일어남)
x=torch.tensor([1.],requires_grad=True) 
y=torch.tensor([1.],requires_grad=True)
z=2*x**2+y**2

print(z)
z.backward()
print(x.grad)
print(y.grad)

tensor([3.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([2.])


In [28]:
x=torch.tensor([1.],requires_grad=True) 
y=torch.tensor([1.],requires_grad=True)
z=y*x**2

print(z)
z.backward()
print(x.grad)
print(y.grad)

tensor([1.], grad_fn=<MulBackward0>)
tensor([2.])
tensor([1.])


In [ ]:
x=torch.tensor([1.,2.,3.],requires_grad=True) # x1 = 1, x2 = 2, x3 = 3이라고 하자
y=torch.sum(x**2) # x1**2+x2**2+x3**2 , 
print(y) 
y.backward() # y=x**2하면 에러 ->  y를 backward()하려면 y는 스칼라여야한다.

print(y)
print(x.grad) # 스칼라를 벡터로 미분

tensor(14., grad_fn=<SumBackward0>)
tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [35]:
x=torch.tensor([1.],requires_grad=True) 
# ~~~코드
x.requires_grad=False # transfer learning(전이학습)할때 필요
# x=x.detach() # x.requires_grad=False대신에 이렇게도 쓸수있다(많이쓰임)

y=x**2
print(y)

x=x.detach()
# y.backward() -> error!

tensor([1.])


In [40]:
# detach와 torch.no_grad(중요!!!!!!!!!!!!111)
x=torch.tensor([1.],requires_grad=True)
# chain rule을 위해 계속 grad_fu를 update하니까 grad_fu 잠시 계산 안하고 싶을때 torch.no_grad
# 모델 테스트 시에는 불필요하게 grad_fu를 메모리 저장할 필요가 없기 때문!( 훈련할땐 미분이 필요하지만 테스트할때는 필요가 없기 떄문이다.)
with torch.no_grad(): # 이 안에서는 gradient function을 계산하지 않는다.(requires_grad를 만지지 않고)
    y=x**2
    print(x.requires_grad)
    print(y)

print('---------------------------')
# y.backward() error!
print(x.requires_grad)
y=x**2
# y.backward() # -> 정상작동
print(y)
# print(x.grad) # -> 위에 정상작동 확인

True
tensor([1.])
---------------------------
True
tensor([1.], grad_fn=<PowBackward0>)


In [ ]:
# 교육자료용 (밑의코드는 anaconda 환경에서 에러 -> 구글 코렙에서 생성함)
import torch
from torchviz import make_dot

x=torch.tensor([1.,2.],requires_grad=True)
make_dot(x) # 박스안의 숫자 -> 변수개수
make_dot(x**2)
make_dot(x**2+1)
# print((x**2+1)**2)

In [ ]:
x=torch.tensor([0.],requires_grad=True)
y=torch.abs(x)

make_dot(y)
# y.backward()
# print(x.grad) # -> 원래 절댓값은 미분 안되는데 0일때만 그냥 예외처리 해놓았다.

### 간단한 인공신경만 만들기

In [5]:
import torch
from torch import nn

x=torch.tensor([1.])
model = nn.Linear(1,1) # 입력 node 한 개, 출력 node 한 개인 layer 만듦

print(model.weight) # 만들면서 initialize 함
print(model.bias)

y = model(x) # 여기선 입력이 그대로 출력으로 나가기 activation function은 linear activation
print(y)


y = x @ model.weight + model.bias
print(y)

Parameter containing:
tensor([[0.1913]], requires_grad=True)
Parameter containing:
tensor([-0.2437], requires_grad=True)
tensor([-0.0525], grad_fn=<ViewBackward0>)
torch.Size([1])
torch.Size([1, 1])
tensor([-0.0525], grad_fn=<AddBackward0>)


In [6]:
fc1 = nn.Linear(1,3) # fully-connected
fc2 = nn.Linear(3,1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

x=torch.tensor([1.])
y = (x@fc1.weight.T+fc1.bias)@fc2.weight.T+fc2.bias
# nn.Linear 는 개x채x행x열에서 "채" 형태로 (1D data) 들어오길 기대하는 녀석이다.
# 즉, 노드 하나가 곧 한 채널의 의미한다.
# 따라서, 데이터 여러개를 통과시키고 싶다면 개x채 의 형태로 줘야 함
# why T? weight도 개x채 형태로 만들기 위함!
# 일단, weight shape 개x채에서 채는 (대부분)무조건 앞에 거 채널 개수와 맞추셈!
# 예를 들어, nn.Linear(2,3) 이면 앞에거 채널 개수는 2 따라서 ?x2 인데
# 두 채널 값을 가지고 3개의 노드를 만드는 거라서 3x2 가 된다!

print(y)
# input size: 1
# fc1.weight.T size: 1x3
# fc1.bias size: 3
# fc2.weight.T size: 3x1
# fc2.bias size: 1

Parameter containing:
tensor([[ 0.5546],
        [-0.1674],
        [-0.6937]], requires_grad=True)
Parameter containing:
tensor([ 0.2915, -0.3864,  0.0387], requires_grad=True)
Parameter containing:
tensor([[0.4192, 0.0455, 0.0406]], requires_grad=True)
Parameter containing:
tensor([0.4560], requires_grad=True)
tensor([ 0.8461, -0.5537, -0.6550], grad_fn=<ViewBackward0>)
tensor([0.7590], grad_fn=<ViewBackward0>)
tensor([0.7590], grad_fn=<AddBackward0>)


In [ ]:
fc1 = nn.Linear(1,3)
fc2 = nn.Linear(3,1)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

model = nn.Sequential(fc1, fc2) # layer 풀칠
x=torch.tensor([1.])
print(model(x))

In [ ]:
model = nn.Sequential(nn.Linear(2,5), # 여기는 채,채
                      nn.Linear(5,10),
                      nn.Linear(10,3))

x=torch.randn(2)
print(x)
print(model(x))

x=torch.randn(1,2)
print(x)
print(model(x))

x=torch.randn(5,2) # 개x채 => 두 개의 채널 값(키, 몸무게)을 가지는 데이터(사람) 5개를 통과시킴
print(x)
print(model(x))

x=torch.randn(2,3,1,4,5,2)
print(model(x).shape)

In [93]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2,5) # xrk (5,2) -> 2개 '채널(특성 이라고 봐도 무방)' 가지니 2로 시작
        self.fc2 = nn.Linear(5,10)
        self.fc3 = nn.Linear(10,3)
        self.sig1 = nn.Sigmoid() # activation function으로 시그모이드함수 사용
        self.sig2 = nn.Sigmoid()
        self.sig3 = nn.Sigmoid()

    def forward(self,x):
        x=self.fc1(x)
        x=self.sig1(x)
        x=self.fc2(x)
        x=self.sig2(x)
        x=self.fc3(x)
        x=self.sig3(x)
        
        return x

model = MyModel()
x=torch.randn(5,2) # 2개채널 가지는 데이터 5개
y = model(x) # y = model.forward(x)과 동일
print(y)

tensor([[0.4778, 0.5248, 0.4686],
        [0.4776, 0.5248, 0.4684],
        [0.4804, 0.5227, 0.4671],
        [0.4809, 0.5199, 0.4635],
        [0.4812, 0.5213, 0.4658]], grad_fn=<SigmoidBackward0>)


In [24]:
print(model)
print(model.fc1.weight) # 만든 모델의 fc1의 weight확인
print(model.fc2.bias) 

MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (sig1): Sigmoid()
  (sig2): Sigmoid()
  (sig3): Sigmoid()
)
Parameter containing:
tensor([[ 0.6755,  0.2762],
        [-0.0646,  0.0959],
        [ 0.5820, -0.2719],
        [-0.2604, -0.0969],
        [-0.5298, -0.4252]], requires_grad=True)
Parameter containing:
tensor([-0.2883, -0.3166,  0.4077,  0.1259, -0.3441, -0.1134, -0.4209,  0.1919,
        -0.0547,  0.4428], requires_grad=True)


In [75]:
# sequential로 묶기

class MyModel2(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Sequential(
        nn.Linear(2,5),
        nn.Sigmoid() ,
        nn.Linear(5,10),
        nn.Sigmoid(),
        nn.Linear(10,3) ,
        nn.Sigmoid()

        )


    def forward(self,x):
        x = self.linear(x)
        return x

model2 = MyModel2()
x=torch.randn(5,2) 
y = model2(x)  # PyTorch에서는 __init__, forward 메서드만이 모델이 호출될 때 실행되는 메서드, 만약 위에서 test메서드가 따로 존재한다면 result = model.test(x)라고 해줘야한다.
print(y)

tensor([[0.4651, 0.3517, 0.5019],
        [0.4647, 0.3528, 0.5004],
        [0.4638, 0.3545, 0.4993],
        [0.4652, 0.3517, 0.5014],
        [0.4637, 0.3546, 0.4988]], grad_fn=<SigmoidBackward0>)


In [76]:
print(model2)
print(model2.linear[0].weight) # 0번째꺼 weight , model2.linear[0] -> 0번째꺼(이때 0번째꺼는 nn.Linear(2,5)이지 nn.Linear(2,5)와 nn.Sigmoid()를 합친게 아니다.)
# model2.linear[-1].weight -> error -> why? -> sigmoid함수는 파라미터가 없다. 하지만 activationn function이 PReLU(parametric ReLU)경우는 음수쪽 기울기를 파라미터로 둔다!! -> 파라미터 loss감소하는 쪽으로 학습된다.
print(model2.linear[-2].bias)

MyModel2(
  (linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)
Parameter containing:
tensor([[ 0.2076, -0.2912],
        [ 0.5510, -0.0655],
        [ 0.1975,  0.3459],
        [ 0.0385, -0.1061],
        [ 0.2308,  0.2851]], requires_grad=True)
Parameter containing:
tensor([ 0.0719, -0.2310, -0.0070], requires_grad=True)


In [80]:
# 모델의 파라미터 확안
list(model2.parameters()) # model.parameters() -> generate 타입 -> list로 바꿔주기-----------------------> 나중에 자세히 하고 정리하기

[Parameter containing:
 tensor([[ 0.2076, -0.2912],
         [ 0.5510, -0.0655],
         [ 0.1975,  0.3459],
         [ 0.0385, -0.1061],
         [ 0.2308,  0.2851]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4625, -0.2321,  0.0373,  0.6399,  0.4151], requires_grad=True),
 Parameter containing:
 tensor([[ 0.2412, -0.3765, -0.3015,  0.0688, -0.1171],
         [-0.0597, -0.4161, -0.3212,  0.3512, -0.2234],
         [ 0.1772, -0.2437,  0.2005, -0.1854, -0.0516],
         [ 0.1190, -0.3116, -0.2440, -0.2048, -0.1024],
         [-0.3911, -0.0199,  0.0078, -0.4410, -0.1776],
         [ 0.1301, -0.4373,  0.3108, -0.1286, -0.1032],
         [ 0.2631, -0.3913,  0.1121, -0.1352, -0.3090],
         [ 0.2813,  0.2058,  0.0373,  0.2405, -0.2470],
         [ 0.1284,  0.2427,  0.1862, -0.1171,  0.0911],
         [ 0.1017, -0.2819,  0.2356,  0.4032, -0.0958]], requires_grad=True),
 Parameter containing:
 tensor([-0.0411,  0.3357,  0.1673, -0.2713, -0.0692, -0.2996, -0.4342,  0.0570,
  

In [91]:
# 파라미터 수 구하기
num = sum([p.numel() for p in model.parameters() if p.requires_grad]) # A.numel()) # 전체 성분의 수 , if p.requires_grad -> '학습' 파라미터의 개수만 세고 싶을때 
print(num)

108


## weight initialization( 그냥 SGG 읽기)

In [ ]:
# 내 필기용 : He initialization 이 공식 문서랑 다르다? => paper에 맞게 구현됐고 torch 공식 문서만 틀림( 지금은 고쳐졌을수도 있음)
# initial weight를 직접 원하는 형태로 바꿔주기
import torch
from torch import nn

Fin=5000
Fout=1000
w = torch.zeros(141, Fin)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu') # forward pass에서 값의 범위를 유지시켜주기 위함
print(w.std())
print(torch.sqrt(torch.tensor(2/Fin)))
w = torch.zeros(Fout, 212)
nn.init.kaiming_uniform_(w, mode='fan_out', nonlinearity='relu') # backward pass에서 값의 범위를 유지시켜주기 위함
print(w.std())
print(torch.sqrt(torch.tensor(2/Fout)))

# CNN?
N=32
C=64
H=6
W=10
w = torch.zeros(N,C,H,W)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu')
print(w.std())
print(torch.sqrt(torch.tensor(2/(C*H*W))))

w = torch.zeros(N,C,H,W)
nn.init.kaiming_uniform_(w, mode='fan_out', nonlinearity='relu')
print(w.std())
print(torch.sqrt(torch.tensor(2/(N*H*W))))